/**
 * Presa da Tempestade Vingativa — item-archetype reference plugin.
 * Source: presa-da-tempestade-vingativa-mecanicas.md
 *
 * Every numeric knob is a config field defaulting to the documented value.
 * The "vs Sworn Threat" charge discount is driven by the vsJurada toggle the
 * wielder flips while fighting the sworn threat.
 */
import type { MechanicPlugin, StateOp } from "../../api";

const gain = (target: string, amount: number | string): StateOp[] => [{ op: "adjust", target, amount }];

/** Spend-on-hit menu: one action per documented cost tier, discounted vs the Sworn Threat. */
function spendAction(tier: 1 | 2 | 3 | 4 | 5 | 6) {
  return {
    id: `spend-${tier}`,
    labelKey: `PRESA.Spend${tier}`,
    descriptionKey: `PRESA.Spend${tier}Hint`,
    costs: [{ resource: "cargas", amount: `max(1, @cfg.spendCost${tier} - @vsJurada)` }],
    ...(tier === 1 ? { roll: { formula: "@cfg.spend1Dice", flavorKey: "PRESA.Spend1Flavor" } } : {}),
  };
}

export const presaTempestade: MechanicPlugin = {
  id: "presa-tempestade",
  version: "1.0.0",
  archetype: "item",
  nameKey: "PRESA.Name",
  descriptionKey: "PRESA.Description",

  trackers: [
    {
      id: "peso",
      labelKey: "PRESA.Peso",
      min: 0,
      max: "@cfg.pesoMax",
      thresholds: [
        { at: 1, labelKey: "PRESA.Peso1", descriptionKey: "PRESA.Peso1Desc" },
        { at: 2, labelKey: "PRESA.Peso2", descriptionKey: "PRESA.Peso2Desc" },
        { at: 3, labelKey: "PRESA.Peso3", descriptionKey: "PRESA.Peso3Desc" },
        { at: 4, labelKey: "PRESA.Peso4", descriptionKey: "PRESA.Peso4Desc" },
        { at: 5, labelKey: "PRESA.Peso5", descriptionKey: "PRESA.Peso5Desc" },
        { at: 6, labelKey: "PRESA.Peso6", descriptionKey: "PRESA.Peso6Desc" },
      ],
    },
    // 1 while a Sworn Threat is declared (drives Guardião stance availability).
    { id: "ameacaJurada", labelKey: "PRESA.AmeacaJurada", min: 0, max: 1 },
    // 1 while currently fighting the Sworn Threat (drives the spend discount).
    { id: "vsJurada", labelKey: "PRESA.VsJurada", min: 0, max: 1 },
  ],

  resources: [
    {
      id: "cargas",
      labelKey: "PRESA.Cargas",
      // Documented: 12 max, reduced to 8 while Peso >= 4.
      max: "@cfg.maxCargas - @cfg.pesoCargaPenalty * gte(@peso, @cfg.pesoPenaltyAt)",
      initial: 0,
      recharge: [{ on: "longRest", setTo: 0, amount: "none" }], // all charges lost on long rest
    },
  ],

  triggers: [
    { id: "hit", labelKey: "PRESA.TrigHit", event: "attack-hit", apply: gain("cargas", "@cfg.gainHit") },
    { id: "damage-taken", labelKey: "PRESA.TrigDamage", event: "damage-taken", apply: gain("cargas", "@cfg.gainHit") },
    { id: "crit", labelKey: "PRESA.TrigCrit", event: "crit-dealt", apply: gain("cargas", "@cfg.gainBig") },
    { id: "kill", labelKey: "PRESA.TrigKill", event: "reduced-to-zero", apply: gain("cargas", "@cfg.gainBig") },
    // Protection/rescue gains can't be auto-detected — manual fallbacks:
    { id: "protect", labelKey: "PRESA.TrigProtect", event: "manual", apply: gain("cargas", "@cfg.gainHit") },
    { id: "rescue", labelKey: "PRESA.TrigRescue", event: "manual", apply: gain("cargas", "@cfg.gainBig") },
    { id: "missed-eye", labelKey: "PRESA.TrigMissedEye", event: "manual", apply: gain("cargas", "@cfg.gainHit") },
    // Oath progress is adjudicated at every long rest while an oath is active.
    { id: "oath-rest", labelKey: "PRESA.TrigOathRest", event: "rest-long", runHook: true, manualFallback: false },
  ],

  prompts: [
    {
      id: "julgamento-info",
      titleKey: "PRESA.Julgamento",
      bodyKey: "PRESA.JulgamentoBody",
      choices: [{ id: "ok", labelKey: "PRESA.Confirm" }],
    },
  ],

  actions: [
    spendAction(1),
    spendAction(2),
    spendAction(3),
    spendAction(4),
    spendAction(5),
    spendAction(6),
    {
      id: "declarar-juramento",
      labelKey: "PRESA.DeclararJuramento",
      descriptionKey: "PRESA.DeclararJuramentoHint",
      forbidsFlag: "juramentoDeclarado",
      apply: [
        { op: "set", target: "ameacaJurada", value: 1 },
        { op: "set", target: "flag:juramentoDeclarado", value: true },
      ],
      adjudicate: "juramento-valido",
    },
    {
      id: "represalia",
      labelKey: "PRESA.Represalia",
      descriptionKey: "PRESA.RepresaliaHint",
      apply: gain("cargas", 1),
      roll: { formula: "@cfg.represaliaDice", flavorKey: "PRESA.RepresaliaFlavor" },
    },
    {
      id: "julgamento",
      labelKey: "PRESA.Julgamento",
      descriptionKey: "PRESA.JulgamentoHint",
      costs: [{ resource: "cargas", amount: "@cfg.julgamentoCost" }],
      roll: { formula: "@cfg.julgamentoDice", flavorKey: "PRESA.JulgamentoFlavor" },
      prompt: "julgamento-info",
      adjudicate: "julgamento-colateral",
    },
    {
      id: "ultimo-trovao",
      labelKey: "PRESA.Ultimate",
      descriptionKey: "PRESA.UltimateHint",
      costs: [{ resource: "cargas", amount: "@cfg.julgamentoCost" }],
      cooldown: { type: "longRest" },
      transform: "avatar-tempestade",
      roll: { formula: "@cfg.ultimateDice", flavorKey: "PRESA.UltimateFlavor" },
    },
  ],

  stances: [
    {
      id: "posturas",
      labelKey: "PRESA.Posturas",
      switchOn: "turn-start",
      allowNone: true,
      stances: [
        {
          id: "relampago",
          labelKey: "PRESA.PosturaRelampago",
          descriptionKey: "PRESA.PosturaRelampagoDesc",
          effects: [
            {
              name: "Relâmpago Predador",
              changes: [{ key: "system.attributes.movement.walk", mode: 2, value: "20" }],
            },
          ],
        },
        {
          id: "trovao",
          labelKey: "PRESA.PosturaTrovao",
          descriptionKey: "PRESA.PosturaTrovaoDesc",
          effects: [{ name: "Trovão Dominador" }],
        },
        {
          id: "olho",
          labelKey: "PRESA.PosturaOlho",
          descriptionKey: "PRESA.PosturaOlhoDesc",
          effects: [{ name: "Olho da Tempestade" }],
        },
        {
          id: "guardiao",
          labelKey: "PRESA.PosturaGuardiao",
          descriptionKey: "PRESA.PosturaGuardiaoDesc",
          effects: [{ name: "Guardião do Juramento" }],
        },
      ],
    },
  ],

  transformations: [
    {
      id: "avatar-tempestade",
      labelKey: "PRESA.AvatarTempestade",
      strategy: "overlay",
      durationRounds: "@cfg.ultimateRounds",
      overlay: {
        effects: [
          {
            name: "Avatar da Última Tempestade",
            changes: [{ key: "system.attributes.movement.fly", mode: 4, value: "120" }],
            description:
              "Crits 16-20; +8d12 elétrico/trovejante por acerto; 1x/turno absorve dano de aliado a 120 ft; imune a charmed/frightened/paralyzed/stunned/derrubado/movido; se cair a 0 PV permanece de pé até o fim do próximo turno.",
          },
        ],
      },
      onExpire: { adjudicate: "preco-ultimate", chatKey: "PRESA.UltimateEnded" },
    },
  ],

  adjudications: [
    {
      id: "juramento-valido",
      titleKey: "PRESA.AdjJuramento",
      descriptionKey: "PRESA.AdjJuramentoDesc",
      kind: "confirm",
      onDeny: [
        { op: "set", target: "ameacaJurada", value: 0 },
        { op: "set", target: "flag:juramentoDeclarado", value: false },
      ],
    },
    {
      id: "oath-progress",
      titleKey: "PRESA.AdjOath",
      descriptionKey: "PRESA.AdjOathDesc",
      kind: "choice",
      choices: [
        { id: "maior", labelKey: "PRESA.OathMajor", apply: [{ op: "adjust", target: "peso", amount: -1 }] },
        { id: "menor", labelKey: "PRESA.OathMinor" },
        { id: "nenhum", labelKey: "PRESA.OathNone", apply: [{ op: "adjust", target: "peso", amount: 1 }] },
      ],
    },
    {
      id: "julgamento-colateral",
      titleKey: "PRESA.AdjColateral",
      descriptionKey: "PRESA.AdjColateralDesc",
      kind: "confirm",
      onConfirm: [{ op: "adjust", target: "peso", amount: 1 }],
    },
    {
      id: "preco-ultimate",
      titleKey: "PRESA.AdjPreco",
      descriptionKey: "PRESA.AdjPrecoDesc",
      kind: "choice",
      choices: [
        { id: "vida", labelKey: "PRESA.PrecoVida" },
        { id: "alma", labelKey: "PRESA.PrecoAlma" },
        { id: "corpo", labelKey: "PRESA.PrecoCorpo" },
        { id: "memoria", labelKey: "PRESA.PrecoMemoria" },
        { id: "juramento", labelKey: "PRESA.PrecoJuramento", apply: [{ op: "set", target: "ameacaJurada", value: 1 }] },
        { id: "inocente", labelKey: "PRESA.PrecoInocente" },
      ],
    },
  ],

  configSchema: [
    { key: "maxCargas", type: "number", labelKey: "PRESA.CfgMaxCargas", default: 12, min: 1, groupKey: "PRESA.CfgGroupCargas" },
    { key: "gainHit", type: "formula", labelKey: "PRESA.CfgGainHit", default: "1", groupKey: "PRESA.CfgGroupCargas" },
    { key: "gainBig", type: "formula", labelKey: "PRESA.CfgGainBig", default: "2", groupKey: "PRESA.CfgGroupCargas" },
    { key: "spendCost1", type: "number", labelKey: "PRESA.CfgSpend1", default: 1, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spendCost2", type: "number", labelKey: "PRESA.CfgSpend2", default: 2, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spendCost3", type: "number", labelKey: "PRESA.CfgSpend3", default: 3, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spendCost4", type: "number", labelKey: "PRESA.CfgSpend4", default: 4, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spendCost5", type: "number", labelKey: "PRESA.CfgSpend5", default: 5, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spendCost6", type: "number", labelKey: "PRESA.CfgSpend6", default: 6, groupKey: "PRESA.CfgGroupSpend" },
    { key: "spend1Dice", type: "dice", labelKey: "PRESA.CfgSpend1Dice", default: "2d8", groupKey: "PRESA.CfgGroupSpend" },
    { key: "pesoMax", type: "number", labelKey: "PRESA.CfgPesoMax", default: 6, min: 1, groupKey: "PRESA.CfgGroupPeso" },
    { key: "pesoPenaltyAt", type: "number", labelKey: "PRESA.CfgPesoPenaltyAt", default: 4, groupKey: "PRESA.CfgGroupPeso" },
    { key: "pesoCargaPenalty", type: "number", labelKey: "PRESA.CfgPesoCargaPenalty", default: 4, groupKey: "PRESA.CfgGroupPeso" },
    { key: "represaliaDice", type: "dice", labelKey: "PRESA.CfgRepresaliaDice", default: "8d8", groupKey: "PRESA.CfgGroupDice" },
    { key: "julgamentoCost", type: "number", labelKey: "PRESA.CfgJulgamentoCost", default: 12, groupKey: "PRESA.CfgGroupDice" },
    { key: "julgamentoDc", type: "formula", labelKey: "PRESA.CfgJulgamentoDc", default: "24", groupKey: "PRESA.CfgGroupDice" },
    { key: "julgamentoDice", type: "dice", labelKey: "PRESA.CfgJulgamentoDice", default: "20d12 + 20d12 + 20d12", groupKey: "PRESA.CfgGroupDice" },
    { key: "ultimateDice", type: "dice", labelKey: "PRESA.CfgUltimateDice", default: "24d12 + 24d12", groupKey: "PRESA.CfgGroupUltimate" },
    { key: "ultimateRounds", type: "number", labelKey: "PRESA.CfgUltimateRounds", default: 10, min: 1, groupKey: "PRESA.CfgGroupUltimate" },
  ],

  hooks: {
    // Long rest with an active oath: queue the DM's progress adjudication.
    async onTrigger(ctx, trigger) {
      if (trigger.id === "oath-rest" && ctx.state.get("ameacaJurada") >= 1) {
        await ctx.queueAdjudication("oath-progress");
      }
    },
  },

  i18n: {
    en: {
      PRESA: {
        Name: "Fang of the Vengeful Storm",
        Description: "Sentient storm spear: charges, stances, a heroic oath and the Storm's Weight.",
        Cargas: "Storm Charges",
        Peso: "Storm's Weight",
        AmeacaJurada: "Sworn Threat active",
        VsJurada: "Fighting the Sworn Threat",
        TrigHit: "Hit with the Fang (+1)",
        TrigDamage: "Took damage (+1)",
        TrigCrit: "Critical hit (+2)",
        TrigKill: "Dropped a relevant enemy (+2)",
        TrigProtect: "Protected someone (+1)",
        TrigRescue: "Saved someone from likely death (+2)",
        TrigMissedEye: "Missed by an attack (Eye of the Storm) (+1)",
        TrigOathRest: "Oath progress (long rest)",
        Spend1: "Spend: +2d8 lightning",
        Spend1Hint: "The hit deals +2d8 lightning damage.",
        Spend1Flavor: "Lightning surges through the wound!",
        Spend2: "Spend: shove 30 ft + prone",
        Spend2Hint: "Target is pushed up to 30 ft and knocked prone.",
        Spend3: "Spend: no reactions/teleport",
        Spend3Hint: "Target loses reactions and cannot teleport until the end of its next turn.",
        Spend4: "Spend: storm arc",
        Spend4Hint: "An arc jumps to a creature within 30 ft for half the attack's total damage.",
        Spend5: "Spend: burn Legendary Resistance",
        Spend5Hint: "CON save DC 22 or lose 1 use of Legendary Resistance.",
        Spend6: "Spend: automatic critical",
        Spend6Hint: "The hit becomes an automatic critical.",
        DeclararJuramento: "Declare Sworn Threat",
        DeclararJuramentoHint: "Bonus action. The DM validates the target as a real threat.",
        Represalia: "Protective Reprisal (reaction)",
        RepresaliaHint: "Teleport 10 ft from the aggressor and strike: +8d8 lightning, +1 charge.",
        RepresaliaFlavor: "Reprisal of the storm!",
        Julgamento: "Storm's Judgement",
        JulgamentoHint: "Spend 12 charges: CON save DC 24 or massive lightning/thunder/piercing damage.",
        JulgamentoBody: "Target makes a CON save (DC per config). On failure: full damage, loses reactions, loses 1 Legendary Resistance, no healing for 1 minute.",
        JulgamentoFlavor: "The sky passes judgement!",
        Confirm: "Roll it",
        AdjColateral: "Judgement: avoidable collateral damage?",
        AdjColateralDesc: "If the Judgement caused avoidable collateral damage or served no protective purpose, the Storm's Weight increases by 1.",
        Ultimate: "Hero's Last Thunder (lvl 24)",
        UltimateHint: "12 charges, 1/long rest. Mass salvation, mass judgement, then the Avatar of the Last Storm.",
        UltimateFlavor: "\"While I breathe, no one else falls.\"",
        UltimateEnded: "The Last Thunder fades. The hero must pay the sky.",
        AvatarTempestade: "Avatar of the Last Storm",
        Posturas: "Storm Stances",
        PosturaRelampago: "Predator Lightning",
        PosturaRelampagoDesc: "+20 ft speed; teleport 30 ft after a hit; +4d8 lightning after teleporting.",
        PosturaTrovao: "Dominating Thunder",
        PosturaTrovaoDesc: "Hit targets get disadvantage on their next attack; wall slams +6d8 thunder.",
        PosturaOlho: "Eye of the Storm",
        PosturaOlhoDesc: "6+ charges: resistance to all damage. Missed attacks grant charges. 10+: immovable.",
        PosturaGuardiao: "Oath Warden",
        PosturaGuardiaoDesc: "Requires a Sworn Threat: +6d8 vs it, it cannot heal within 120 ft, no invisibility vs you.",
        AdjJuramento: "Validate Sworn Threat",
        AdjJuramentoDesc: "Reject if the threat is too small, selfish, or not a real danger.",
        AdjOath: "Oath progress since last long rest?",
        AdjOathDesc: "Major advance: Weight -1. Minor: unchanged. None/evasion: Weight +1.",
        OathMajor: "Major advance (-1 Weight)",
        OathMinor: "Minor advance",
        OathNone: "No advance (+1 Weight)",
        AdjPreco: "The Hero Pays the Sky — choose a price",
        AdjPrecoDesc: "Refusing to choose means the Fang picks two prices. Record it on the sheet.",
        PrecoVida: "Life: -24 max HP permanently",
        PrecoAlma: "Soul: gain a Storm Scar",
        PrecoCorpo: "Body: 2 levels of unremovable exhaustion",
        PrecoMemoria: "Memory: lose a core heroic memory",
        PrecoJuramento: "Oath: the Fang swears a new, vast threat",
        PrecoInocente: "Marked Innocent: someone saved bears the Storm Mark",
        Peso1: "Weight 1", Peso1Desc: "The weapon whispers accusations; disadvantage to lie about your heroics.",
        Peso2: "Weight 2", Peso2Desc: "-10 ft speed when moving away from endangered innocents.",
        Peso3: "Weight 3", Peso3Desc: "First ally/innocent downed within 120 ft each day: 6d12 lightning to you.",
        Peso4: "Weight 4", Peso4Desc: "Max Storm Charges reduced from 12 to 8.",
        Peso5: "Weight 5", Peso5Desc: "Offensive abilities while someone nearby is dying: you take half the damage.",
        Peso6: "Weight 6", Peso6Desc: "The weapon may seize control for 1 round to force a rescue.",
        CfgGroupCargas: "Charges", CfgGroupSpend: "Spend menu", CfgGroupPeso: "Storm's Weight",
        CfgGroupDice: "Dice & DCs", CfgGroupUltimate: "Ultimate",
        CfgMaxCargas: "Maximum charges", CfgGainHit: "Standard gain", CfgGainBig: "Major gain",
        CfgSpend1: "Cost: bonus lightning", CfgSpend2: "Cost: shove", CfgSpend3: "Cost: lockdown",
        CfgSpend4: "Cost: storm arc", CfgSpend5: "Cost: burn LR", CfgSpend6: "Cost: auto-crit",
        CfgSpend1Dice: "Bonus lightning dice",
        CfgPesoMax: "Weight maximum", CfgPesoPenaltyAt: "Charge penalty at Weight", CfgPesoCargaPenalty: "Charge penalty amount",
        CfgRepresaliaDice: "Reprisal bonus dice", CfgJulgamentoCost: "Judgement cost",
        CfgJulgamentoDc: "Judgement save DC", CfgJulgamentoDice: "Judgement damage",
        CfgUltimateDice: "Ultimate damage", CfgUltimateRounds: "Avatar duration (rounds)",
      },
    },
    "pt-BR": {
      PRESA: {
        Name: "Presa da Tempestade Vingativa",
        Description: "Lança-tempestade senciente: cargas, posturas, juramento heroico e o Peso da Tempestade.",
        Cargas: "Cargas de Tempestade",
        Peso: "Peso da Tempestade",
        AmeacaJurada: "Ameaça Jurada ativa",
        VsJurada: "Enfrentando a Ameaça Jurada",
        TrigHit: "Acertou com a Presa (+1)",
        TrigDamage: "Sofreu dano (+1)",
        TrigCrit: "Acerto crítico (+2)",
        TrigKill: "Reduziu inimigo relevante a 0 PV (+2)",
        TrigProtect: "Protegeu alguém (+1)",
        TrigRescue: "Salvou alguém de morte provável (+2)",
        TrigMissedEye: "Ataque errou você (Olho da Tempestade) (+1)",
        TrigOathRest: "Avanço do Juramento (descanso longo)",
        Spend1: "Gasto: +2d8 elétrico",
        Spend1Hint: "O acerto causa +2d8 de dano elétrico.",
        Spend1Flavor: "Relâmpagos irrompem da ferida!",
        Spend2: "Gasto: empurrão 30 ft + caído",
        Spend2Hint: "O alvo é empurrado até 30 ft e fica caído.",
        Spend3: "Gasto: sem reações/teleporte",
        Spend3Hint: "O alvo perde reações e não pode se teleportar até o fim do próximo turno dele.",
        Spend4: "Gasto: arco de tempestade",
        Spend4Hint: "Um arco salta para uma criatura a até 30 ft causando metade do dano total do ataque.",
        Spend5: "Gasto: queimar Resistência Lendária",
        Spend5Hint: "Teste de CON CD 22 ou perde 1 uso de Resistência Lendária.",
        Spend6: "Gasto: crítico automático",
        Spend6Hint: "O acerto se torna um crítico automático.",
        DeclararJuramento: "Declarar Ameaça Jurada",
        DeclararJuramentoHint: "Ação bônus. O Mestre valida se a ameaça é real.",
        Represalia: "Represália Protetora (reação)",
        RepresaliaHint: "Teleporte a 10 ft do agressor e ataque: +8d8 elétrico, +1 carga.",
        RepresaliaFlavor: "Represália da tempestade!",
        Julgamento: "Julgamento da Tempestade",
        JulgamentoHint: "Gaste 12 cargas: teste de CON CD 24 ou dano massivo elétrico/trovejante/perfurante.",
        JulgamentoBody: "O alvo faz teste de CON (CD conforme configuração). Em falha: dano total, perde reações, perde 1 Resistência Lendária e não recupera PV por 1 minuto.",
        JulgamentoFlavor: "O céu julga!",
        Confirm: "Rolar",
        AdjColateral: "Julgamento: dano colateral evitável?",
        AdjColateralDesc: "Se o Julgamento causou dano colateral evitável ou não serviu para proteger, o Peso da Tempestade aumenta em 1.",
        Ultimate: "Último Trovão do Herói (nv 24)",
        UltimateHint: "12 cargas, 1/descanso longo. Salvação em massa, julgamento em massa e o Avatar da Última Tempestade.",
        UltimateFlavor: "\"Enquanto eu respirar, ninguém mais cai.\"",
        UltimateEnded: "O Último Trovão se dissipa. O herói paga o céu.",
        AvatarTempestade: "Avatar da Última Tempestade",
        Posturas: "Posturas da Tempestade",
        PosturaRelampago: "Relâmpago Predador",
        PosturaRelampagoDesc: "+20 ft de deslocamento; teleporte de 30 ft após acertar; +4d8 elétrico após teleportar.",
        PosturaTrovao: "Trovão Dominador",
        PosturaTrovaoDesc: "Alvos atingidos têm desvantagem no próximo ataque; esmagar contra parede: +6d8 trovejante.",
        PosturaOlho: "Olho da Tempestade",
        PosturaOlhoDesc: "6+ cargas: resistência a todo dano. Ataques que erram geram carga. 10+: imóvel contra a sua vontade.",
        PosturaGuardiao: "Guardião do Juramento",
        PosturaGuardiaoDesc: "Exige Ameaça Jurada: +6d8 contra ela, ela não recupera PV a 120 ft, invisibilidade não funciona contra você.",
        AdjJuramento: "Validar Ameaça Jurada",
        AdjJuramentoDesc: "Rejeite se a ameaça for pequena demais, egoísta ou sem perigo real.",
        AdjOath: "Avanço do Juramento desde o último descanso longo?",
        AdjOathDesc: "Avanço maior: Peso -1. Menor: mantém. Nenhum/evasão: Peso +1.",
        OathMajor: "Avanço maior (-1 Peso)",
        OathMinor: "Avanço menor",
        OathNone: "Sem avanço (+1 Peso)",
        AdjPreco: "O Herói Paga o Céu — escolha um preço",
        AdjPrecoDesc: "Recusar significa que a Presa escolhe dois preços. Registre na ficha.",
        PrecoVida: "Vida: -24 PV máximos permanentes",
        PrecoAlma: "Alma: ganha uma Cicatriz da Tempestade",
        PrecoCorpo: "Corpo: 2 níveis de exaustão não removíveis",
        PrecoMemoria: "Memória: perde uma memória heroica importante",
        PrecoJuramento: "Juramento: a Presa jura uma nova ameaça colossal",
        PrecoInocente: "Inocente Marcado: alguém salvo recebe a Marca da Tempestade",
        Peso1: "Peso 1", Peso1Desc: "A arma sussurra acusações; desvantagem para mentir sobre seus atos heroicos.",
        Peso2: "Peso 2", Peso2Desc: "-10 ft de deslocamento ao se afastar de inocentes em perigo claro.",
        Peso3: "Peso 3", Peso3Desc: "Primeiro aliado/inocente caído a 120 ft por dia: 6d12 elétrico em você.",
        Peso4: "Peso 4", Peso4Desc: "Máximo de Cargas de Tempestade cai de 12 para 8.",
        Peso5: "Peso 5", Peso5Desc: "Habilidade ofensiva com alguém morrendo a 60 ft: você sofre metade do dano causado.",
        Peso6: "Peso 6", Peso6Desc: "A arma pode tomar controle por 1 rodada para forçar um resgate.",
        CfgGroupCargas: "Cargas", CfgGroupSpend: "Menu de gastos", CfgGroupPeso: "Peso da Tempestade",
        CfgGroupDice: "Dados e CDs", CfgGroupUltimate: "Ultimate",
        CfgMaxCargas: "Cargas máximas", CfgGainHit: "Ganho padrão", CfgGainBig: "Ganho maior",
        CfgSpend1: "Custo: elétrico bônus", CfgSpend2: "Custo: empurrão", CfgSpend3: "Custo: bloqueio",
        CfgSpend4: "Custo: arco", CfgSpend5: "Custo: queimar RL", CfgSpend6: "Custo: crítico automático",
        CfgSpend1Dice: "Dados do elétrico bônus",
        CfgPesoMax: "Peso máximo", CfgPesoPenaltyAt: "Penalidade de cargas no Peso", CfgPesoCargaPenalty: "Redução de cargas",
        CfgRepresaliaDice: "Dados da Represália", CfgJulgamentoCost: "Custo do Julgamento",
        CfgJulgamentoDc: "CD do Julgamento", CfgJulgamentoDice: "Dano do Julgamento",
        CfgUltimateDice: "Dano da Ultimate", CfgUltimateRounds: "Duração do Avatar (rodadas)",
      },
    },
  },
};
